services:
  top.api:
    platform: linux/amd64
    image: ghcr.io/thunderstruck71/nestjs-top-api/top-api:develop
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
